(in-package :jingoh.documentizer)

(defun about-symbols(meta-data)
  (flet((PUT(section)
	  (With-doc-directory((merge-pathnames(Section-path section)))
	    (format t "# ~{~A~^, ~}~&"(mapcar #'Escape-*(Section-names section)))
	    (about-symbol (Section-body section)))))
    (dolist(section(Meta-data-singles meta-data))
      (PUT section))
    (dolist(section(Meta-data-commons meta-data))
      (PUT section))))

(defun about-symbol (body)
  (labels((REC(list)
	    (unless(endp list)
	      (BODY (car list)(cdr list))))
	  (BODY(elt rest)
	    (cond
	      ((uiop:string-prefix-p ";;;; " elt)
	       (write-string "## ")
	       (write-line elt *standard-output* :start 5))
	      ((uiop:string-prefix-p ";;; " elt)
	       (write-string "### ")
	       (write-line elt *standard-output* :start 4))
	      ((uiop:string-prefix-p ";; " elt)
	       (write-string "#### ")
	       (write-line elt *standard-output* :start 3))
	      ((uiop:string-prefix-p "; " elt)
	       (write-line elt *standard-output* :start 2))
	      ((uiop:string-prefix-p "#?" elt)
	       (write-line "```lisp")
	       (write-line elt)
	       (write-string (car rest))
	       (write-char #\space)
	       (write-line (cadr rest))
	       (loop :with ops = 0
		     :for (key value) :on (cddr rest) :by #'cddr
		     :while (uiop:string-prefix-p "," key)
		     :do (write-string key)
		     (write-char #\space)
		     (write-line value)
		     (incf ops)
		     :finally (format t "```~2%")
		     (setf rest (nthcdr (+ 2 (* 2 ops))rest))))
	      ((uiop:string-prefix-p "#+syntax" elt)
	       (write-string "### ")
	       (write-line (Escape-* elt) *standard-output* :start 2))
	      ((uiop:string-prefix-p "#+setf" elt)
	       (write-string "### ")
	       (write-line (escape-* elt) *standard-output* :start 2))
	      ((uiop:string-prefix-p "#+signature" elt)
	       (write-string "### ")
	       (write-line (escape-* elt) *standard-output* :start 12))
	      ((uiop:string-prefix-p "#| " elt)
	       (write-string "# ")
	       (write-line elt *standard-output* 
			   :start 3 :end (- (length elt) 2)))
	      (t nil)); discard
	    (REC rest)))
    (REC body)))

